# Generated by Django 3.2.5 on 2021-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angikadesignapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='mention_with_pink_bg',
            field=models.BooleanField(default=False),
        ),
    ]
